version: 2.1
jobs:
  build:
    docker:
      - image: typelead/eta:latest
    steps:
    - checkout

    - restore_cache:
        key: wai-servlet-etlas-v1200-cache-

    - run:
        name: Reset etlas repo
        working_directory: ~/.etlas/patches 
        command: git reset --hard
        
    - run: etlas update

    - run: etlas install

    - save_cache:
        key: wai-servlet-etlas-v1200-cache-{{ epoch }}
        paths:
          - "~/.etlas/config"
          - "~/.etlas/packages"
          - "~/.etlas/patches"
          - "~/.etlas/tools"

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
